<table width="900" cellpadding="0" cellspacing="0" align="center" style="background-color:#000000;">
<tr>
	<td width="280"><img src="images/top_left.gif" alt="" width="280" height="164" /></td>
	<td width="340"><a href="http://www.databusinesssystems.com/"><img src="images/top_center.gif" alt="Data Business Systems" title="Data Business Systems" width="340" height="164" border="0" /></a></td>
	<? if($_SERVER['PHP_SELF'] == "/index.html"){ ?>
	<td width="280" style="background-image:url(images/top_right.gif);" align="right" valign="bottom"><a href="https://www.databusinesssystems.com/account/"><img src="images/login.gif" alt="Customer Account Login" style="margin:30px;" border="0" /></a></td>
	<? }else{ ?>
	<td width="280"><img src="images/top_right.gif" alt="" width="280" height="164" /></td>
	<? } ?>
</tr>
</table>
<table width="900" cellpadding="0" cellspacing="0" align="center" style="background-color:#FFFFFF;">
<tr>
	<td style="width:900px;height:75px;background-image:url(images/middle.gif);text-align:center;vertical-align:middle;"><div style="margin:5px 140px 5px 140px;"><b>Data Business Systems provides business forms, medical claim and healthcare forms, software compatible forms, custom and commercial printing for all your office needs.</b></div></td>
</tr>
<tr>
	<td style="background-image:url(images/main_bg.gif);">
		<div style="margin:0 100px 10px 100px;">
