<?php
/**
 * Jalak
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Jalak
 * @package     Jalak_Zeroprice
 * @author      Hendrathings <hendrathings@gmail.com>
 */
?>
<?php $_zeroPriceHelper = Mage::helper('jalak_zeroprice'); ?>
<?php if ($_zeroPriceHelper->getCanAddToCart()): ?>
    <?php if ($this->getWishlist()->getItemsCount() && $this->getWishlist()->isSalable()): ?>
        <button type="button" title="<?php echo $this->__('Add All to Cart') ?>" onclick="addAllWItemsToCart()" class="button btn-add"><span><span><?php echo $this->__('Add All to Cart') ?></span></span></button>
    <?php endif; ?>
<?php endif; ?>
