<?php 
$_product = $this->getProduct(); 

  $enbleModule=Mage::helper('sourav_quantitydropdown')->isEnabled();              
?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Qty:') ?></label>

	   
<?php 
        if($enbleModule && $this->hasSimpleQuantity()){
           
             $arrayQuantity=$this->getQuantityOptions();
			 
			 
			 
		
?>	   

<select name="qty" class="required-entry" id="qty">
<option value=""></option>
<?php 
   foreach($arrayQuantity as $optionValue){
?>
<option value="<?php echo $optionValue;?>"><?php echo $optionValue;?></option>
<?php }?>

</select>

<?php }else{?>
       <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <?php }endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" id="product-addtocart-button" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
