<?php
/**
 * Jalak
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Jalak
 * @package     Jalak_Zeroprice
 * @author      Hendrathings <hendrathings@gmail.com>
 */
$_zeroPriceHelper = Mage::helper('jalak_zeroprice');
?>

<?php $_product = $this->getProduct() ?>
<?php if ($_zeroPriceHelper->getCanAddToCart() || $_product->getTypeID() == "bundle"): ?>
    <?php if ($_product->isSaleable()): ?>
        <div class="add-to-cart">
            <?php if (!$_product->isGrouped()): ?>
                <label for="qty"><?php echo $this->__('Qty:') ?></label>
                <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getMinimalQty($_product) ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
            <?php endif; ?>
            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            <?php echo $this->getChildHtml('', true, true) ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <?php if ($_product->price > $_zeroPriceHelper->priceValue()): ?>
        <div class="add-to-cart">
            <?php if (!$_product->isGrouped()): ?>
                <label for="qty"><?php echo $this->__('Qty:') ?></label>
                <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getMinimalQty($_product) ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
            <?php endif; ?>
            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            <?php echo $this->getChildHtml('', true, true) ?>
        </div>
    <?php endif; ?>
<?php endif; ?>


