<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html>
<head>
	<title>dbs - errors</title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>

<body>
<? include("header.inc"); ?>
<div align="center"><b>Latest Errors Generated by PHP</b></div>
<br>
<?
$array = split("\n",trim(`tail /usr/home/dbs/php_errors`));
foreach(array_reverse($array) as $x)
	print $x."<br><br>";
include("footer.inc");
?>
</body>
</html>
