	</td>
</tr>
</table>
<table width="800" cellpadding="0" cellspacing="0" border="0"  align="center">
<tr><td align="left" colspan="3"><img src="<?=DOCUMENT_BASE?>/images/bottom_bar.gif" width="800" height="37" alt="" border="0"></td><tr>
<tr><td align="right" col><div align="right" style="font-size:10px;">Copyright &copy; 2003-2004 <a href="http://www.databusinesssystems.com">Data Business Systems</a></div></td></tr>
</table>
